<?php

use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        }
        \Illuminate\Support\Facades\DB::table('orders')->truncate();
        \Illuminate\Support\Facades\DB::table('orders')->insert([
            [
                'id' => 1,
                'account_id' => 2,
                'od_code' => 'A001',
                'od_total_price' => 9786000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 390 Cầu Giấy, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays()->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 2,
                'account_id' => 3,
                'od_code' => 'A002',
                'od_total_price' => 15790000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 10 Toàn nhà ACB Trung Hòa Nhân Chính, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 2,
            ],
            [
                'id' => 3,
                'account_id' => 4,
                'od_code' => 'A003',
                'od_total_price' => 7980000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 10 Đường Lê Văn Lương, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'od_status' => 3,
            ],
            [
                'id' => 4,
                'account_id' => 5,
                'od_code' => 'A004',
                'od_total_price' => 5490000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 223 Đội Cấn, Ba Đình, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'od_status' => 4,
            ],
            [
                'id' => 5,
                'account_id' => 6,
                'od_code' => 'A005',
                'od_total_price' => 3595000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 360 Ngô Quyền, Hà Đông, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 5,
            ],
            [
                'id' => 6,
                'account_id' => 7,
                'od_code' => 'A006',
                'od_total_price' => 15890000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 10 Toàn nhà ACB Trung Hòa Nhân Chính, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 7,
                'account_id' => 8,
                'od_code' => 'A007',
                'od_total_price' => 10488000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 233 Hoàng Mai, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'od_status' => 2,
            ],
            [
                'id' => 8,
                'account_id' => 9,
                'od_code' => 'A008',
                'od_total_price' => 15476000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 300 Liễu Giai, Ba Đình, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'od_status' => 3,
            ],
            [
                'id' => 9,
                'account_id' => 10,
                'od_code' => 'A009',
                'od_total_price' => 14470000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 140 Liễu Giai, Ba Đình, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 10,
                'account_id' => 11,
                'od_code' => 'A010',
                'od_total_price' => 5549000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 300 Bách Khoa, Hai Bà Trưng, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng đến nơi gọi vào số điện thoại này 0123412323',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'od_status' => 2,
            ],
            [
                'id' => 11,
                'account_id' => 12,
                'od_code' => 'A011',
                'od_total_price' => 11078000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 30 Nguyễn Trãi ngách 30, Thánh Xuân, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Ngách hợp nhỏ',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-12)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-11)->format('Y-m-d H:i:s'),
                'od_status' => 4,
            ],
            [
                'id' => 12,
                'account_id' => 13,
                'od_code' => 'A012',
                'od_total_price' => 19639000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 30 Ngô Quyền, Hà Đông, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng vào giờ chiều tối',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'od_status' => 3,
            ],
            [
                'id' => 13,
                'account_id' => 14,
                'od_code' => 'A013',
                'od_total_price' => 4089000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Tầng 18 phòng 18A03 Số 21 Lê Văn Lương, Thanh Xuân, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Khi đến nơi gọi điên cho anh Nguyễn Văn Tùng số điện thoại 0249198978',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 14,
                'account_id' => 15,
                'od_code' => 'A014',
                'od_total_price' => 21880000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 162 Bách Khoa, Hai Bà Trưng, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Khi đến nơi gọi điên đến số máy số điện thoại 0242139078',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'od_status' => 2,
            ],
            [
                'id' => 15,
                'account_id' => 16,
                'od_code' => 'A015',
                'od_total_price' => 15666000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 20 Lê Thanh Nghị, Hai Bà Trưng, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Khi đến nơi gọi điên đến số máy số điện thoại 0242139078',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'od_status' => 3,
            ],
            [
                'id' => 16,
                'account_id' => 17,
                'od_code' => 'A016',
                'od_total_price' => 26880000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 20 Lê Thanh Nghị, Hai Bà Trưng, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Khi đến nơi gọi điên đến số máy số điện thoại 0242139078',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'od_status' => 5,
            ],
            [
                'id' => 17,
                'account_id' => 18,
                'od_code' => 'A017',
                'od_total_price' => 10380000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 18 Tố Hữu, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 18,
                'account_id' => 19,
                'od_code' => 'A018',
                'od_total_price' => 10370000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 68 Mỹ Đình Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 2,
            ],
            [
                'id' => 19,
                'account_id' => 20,
                'od_code' => 'A019',
                'od_total_price' => 9880000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 39 Cầu giấy, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 1,
            ],
            [
                'id' => 20,
                'account_id' => 21,
                'od_code' => 'A020',
                'od_total_price' => 7094000,
                'ship_name' => 'Trường Thái Hoàn',
                'ship_address' => 'Số 121 Đội Cấn, Hà Nội',
                'ship_email' => 'hoangtt@gmail.com',
                'ship_phone' => '0243112312',
                'od_note' => 'Giao hàng trong giờ hành chính',
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'od_status' => 5,
            ],
        ]);
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        }
    }
}
